### ISSUE TITLE
Not having covers breaks site generation

### ISSUE THREAD

**Issue by radioactive-penguin** [darshanbaral/kitab#2]
If I attempt to create a _title.md file with the contents of: 

+++ title = "Pride and Prejudice" author = "Jane Austen" date = "2019-05-12" weight = 3 bookCover = "bookCovers/pride_and_prejudice.jpg" +++ 

but I omit the book cover info (leaving me with)+++ title = "Pride and Prejudice" author = "Jane Austen" date = "2019-05-12"  +++

I get the error EOF looking for end TOML front matter delimiter.

Is it possible to build without having the book cover info in the index? I don't have covers for any of my works, so that field isn't necessary.

**Comment by darshanbaral** [comment]
I was not able to reproduce the error @jocelyngould. What version of `hugo` are you using?

**Comment by radioactive-penguin** [comment]
Hugo Static Site Generator v0.58.3/extended linux/amd64 BuildDate: unknown. 

On Manjaro, installed from the AUR.

**Comment by darshanbaral** [comment]
hmm.. I can't reproduce the error but I did update the theme in https://github.com/darshanbaral/kitab/commit/6607ccf50ebd11f9c4ab64ac28103d5ba61253a4 to have an example without cover.

The demo is in https://kitabdemo.netlify.com/
